name: GitHub Pages Build

on:
  workflow_dispatch: {}
  # push:
  #   branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ★ここで JSON を生成する
      - name: Export JSON
        run: |
          python cloud_export_json.py sample metalsound

      # public/ を Pages artifact にアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4